# Generated by Django 4.2.2 on 2023-07-07 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_perro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
